import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ReviewCard } from "@/components/ReviewCard";

const inter = Inter({ subsets: ["latin"] });

// floating action button to scroll
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <main className="flex flex-col min-h-screen bg-black border-2">
        <div className="border-b-2 w-full h-[70px] flex items-center">
          <h1 className="text-3xl">GrayQuarter</h1>
        </div>
        <div className="bg-back min-h-screen flex justify-center items-center">
          {/* intro div */}
          <div className="text-3xl">GrayQuarter</div>
        </div>
        {/* review div */}
        {/* services div */}
        {/* companies we work withdiv */}
        <div className="bg-white min-h-screen flex justify-center items-center"></div>
        {/* contact div */}

        <div></div>
      </main>
    </>
  );
}
